baseURL = 'https://fangyi.io/'
languageCode = 'en-gb'
title = 'Fangyi Zhou'
theme = 'archie'
copyright = 'Fangyi Zhou Â© CC BY 4.0'
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "Posts"
  weight = 2
  identifier = "post"
  url = "/post"
[[menu.main]]
  name = "Publications"
  weight = 3
  identifier = "pub"
  url = "/publication"
[[menu.main]]
  name = "Talks"
  weight = 4
  identifier = "talks"
  url = "/talks"
[[menu.main]]
  name = "About"
  weight = 5
  identifier = "about"
  url = "/about"

[params]
  mode = "auto"
  useCDN = false
  mainSections = ["post"]
  katex = true

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/fangyi-zhou"

[[params.social]]
  name = "Threads"
  icon = "simple:threads"
  url = "https://www.threads.com/@fangyi.zhou_"

[[params.social]]
  name = "ORCID"
  icon = "simple:orcid"
  url = "https://orcid.org/0000-0002-8973-0821"

[[params.social]]
  name = "Google Scholar"
  icon = "simple:googlescholar"
  url = "https://scholar.google.com/citations?user=PPEUHmwAAAAJ"

[permalinks]
  post = '/:year/:month/:title/'
  publication = '/publication/:year/:title/'
